name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 16 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download
        shell: bash
        run: |
          
          rm *.pack
          
          wget --content-disposition www.mindmotion.com.cn/getfile.aspx?id=765
          unzip -o *.zip
          if  ls *.pack >/dev/null 2>&1; then
            rm *.zip
          else
            for dir in `ls $1`;
            do 
              if [ -d $dir ]; then 
                cp -r $dir/* ./; 
                rm -rf $dir; 
              fi
            done
            rm *.zip
          fi
          
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.9.1
        with:
          push_options: '--force'
